export class GlobalConstants {
    public static options: any = [
        { formControlName: "status", label: "App Status", type: "radio" },
        { formControlName: "is_score_available", label: "Score Available", type: "radio" },
        { formControlName: "enable_check_upload_car_images", label: "Activate the feature of requesting to upload car photos", type: "radio" },
        { formControlName: "contact_us", label: "Phone Number For Contact Us", type: "text" },
        { formControlName: "sos", label: "Emergency Number", type: "text" },
        { formControlName: "temporary_block_duration", label: "Temporary block duration (days)", type: "text" },
        { formControlName: "radius", label: "Radius (For Driver Search / Meter)", type: "text" },
        { formControlName: "Timer", label: "Timer (Seconds)", type: "text" },
        { formControlName: "fake_end_trip_m", label: "Distance For Fake Trip (Meter)", type: "text" },
        { formControlName: "fake_end_trip_t", label: "Fake End Trip (Minutes)", type: "text" },
        { formControlName: "try_num", label: "Maximum number of times a search can be attempted", type: "text" },
        { formControlName: "max_near_drivers", label: "Maximum number of drivers nearby", type: "text" },
        { formControlName: "driver_offline_wallet_value", label: "Driver Offline wallet value", type: "text" },
        { formControlName: "rider_account_restriction", label: "Rider Account Restriction", type: "text" },
        { formControlName: "arrival_radius", label: "Arrival Radius", type: "text" },
        { formControlName: "confirm_radius", label: "Confirm Radius", type: "text" },
        { formControlName: "need_documents_days_count", label: "Number of days to send notice of late attachments", type: "text" },
        { formControlName: "offline_driver_days_count", label: "The number of days the driver stays offline to send a reminder notification", type: "text" },
        { formControlName: "passive_rider_days_count", label: "The number of days the rider does not make trip, to send a reminder notification", type: "text" },
        { formControlName: "amount_money_to_rider", label: "Amount Money To Rider", type: "text" },
        { formControlName: "max_discount_wallet", label: "Max discount wallet when create account", type: "text" },
        { formControlName: "max_driver_transfer_wallet", label: "Max Driver Transfer Wallet", type: "text" },
        { formControlName: "prepaid_card_branches_link", label: "Prepaid Card Branches Link", type: "text" },
        { formControlName: "allowed_delay_rider_min", label: "Allowed delay time for the passenger in minutes", type: "text" },
        { formControlName: "rider_delay_cost_per_minute", label: "Delay cost per minute", type: "text" },
        { formControlName: "percentage_exceeded_price_to_compared", label: "The ratio by which it compares to the expected price", type: "text" },
        { formControlName: "distance_between_rider_and_pickup_to_enable_waiting_account", label: "The minimum distance to activate the waiting time calculation in metres", type: "text" },
        { formControlName: "cancel_compensate_price", label: "Compensation amount to the driver when a trip is closed", type: "text" },
        { formControlName: "cancel_compensate_per_day", label: "The number of compensation times for the driver when canceling trips per day", type: "text" },
        { formControlName: "cancel_compensate_time_min", label: "Duration in minutes to drive to calculate compensation for the driver", type: "text" },
        { formControlName: "cancel_compensate_radius_meter", label: "Driving distance to calculate driver compensation", type: "text" },
        { formControlName: "day_to_must_upload_car_images", label: "Number of days to re-upload pictures of the car", type: "text" },

        { formControlName: "value_type", label: "Value Type", type: "select" },
        { formControlName: "taxisti_fee", label: "Taxi Fee", type: "number" },
        { formControlName: "trip_cancellation_fee_after_accepting_in_time", label: "Trip Cancellation Fee After Accepting In Time", type: "text" },
        { formControlName: "trip_cancellation_fee_after_accepting_after_time", label: "Trip Cancellation Fee After Accepting After Time", type: "text" },
        { formControlName: "minute_after_accept", label: "The number of minutes in which the flight cancellation discount account differs after accept", type: "text" },
        { formControlName: "trip_cancellation_fee_after_starting", label: "Cancellation Fee After Starting Trip", type: "text" },
        { formControlName: "trip_cancellation_fee_befor_driver", label: "Trip Cancellation Fee Before Driver", type: "text" },
        { formControlName: "turbo_fee", label: "Turbo Fee", type: "text" },
        { formControlName: "is_min_ride_price_enable", label: "Enable Minimum Ride Price", type: "radio" },
        { formControlName: "min_ride_price_economy", label: "Economy Ride Minimum Price", type: "number" },
        { formControlName: "min_ride_price_women", label: "Women Ride Minimum Price", type: "number" },
        { formControlName: "min_ride_price_luxury", label: "Luxury Ride Minimum Price", type: "number" },

        { formControlName: "app_start_time", label: "App Start Time", type: "text" },
        { formControlName: "app_close_time", label: "App Close Time", type: "text" },

        { formControlName: "expitional_discount_status", label: "Status", type: "radio" },

        { formControlName: "invitations_settings", label: "Invitations Settings", type: "text" },
        { formControlName: "invitation_amount_to_invited", label: "Invitation Amount For invitee", type: "number" },
        { formControlName: "invitation_amount_for_invited", label: "Invitation Amount For inviter", type: "number" },

        { formControlName: "contact_us_driver_approved", label: "Driver Approved", type: "text" },
        { formControlName: "contact_us_driver_not_approved", label: "Driver Not Approved", type: "text" },
        { formControlName: "contact_us_rider_active", label: "Rider Active", type: "text" },
        { formControlName: "contact_us_rider_passive", label: "Rider Passive", type: "text" },
        { formControlName: "sos_link", label: "SOS Link", type: "text" },
        { formControlName: "facebook_page_id", label: "Facebook page Id", type: "number" },
        { formControlName: "google_api_key", label: "Google Api key", type: "text" },

        { formControlName: "android_version", label: "Android", type: "text" },
        { formControlName: "android_force_update", label: "Force Update", type: "text" },
        { formControlName: "ios_version", label: "Ios", type: "text" },
        { formControlName: "ios_force_update", label: "Force Update", type: "text" },
    ];
}